### ISSUE TITLE
gcc too old on Linux builders

### ISSUE THREAD

**Issue by pitrou** [Anaconda-Server/binstar-build#51]
See:
https://anaconda.org/antoine/llvmlite/builds/20/0
https://anaconda.org/antoine/llvmlite/builds/19/0 (different error message, but probably same underlying reason)

"""
215The selected GCC C++ compiler is not new enough to build LLVM. Please upgrade

216to GCC 4.7. You may pass --disable-compiler-version-checks to configure to

217bypass these sanity checks.
"""

(would be nice to fix that log window for better copy/paste experience, btw :-))

**Comment by mutirri** [comment]
Now public queue - the default one (`build/binstar/public`) has installed:
a) `gcc` in version `4.8.2`,
b) `llvm` (`clang++/clang`) in version `3.3`.

The private `build-binstar-continuum` queue has also the same software available.

Feel free to use them.
