### ISSUE TITLE
jinja2 missing on some builders

### ISSUE THREAD

**Issue by pitrou** [Anaconda-Server/binstar-build#56]
jinja2 is a requirement when using templating conda-build configuration (meta.yaml)

See:
https://anaconda.org/antoine/llvmlite/builds/19/3
https://anaconda.org/antoine/llvmlite/builds/19/4

**Comment by mutirri** [comment]
These errors are 6 days old.
In last Thursday I installed `jinja2` package on all `linux` and `windows` machines.
So, right now this error should not appear for them anymore.
